"""add model, tool, knowledge_base, settings resources

Revision ID: 76ef965dd961
Revises: d6808b67ffea
Create Date: 2026-08-18 18:41:05.047084

"""
from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from alembic import op

revision: str = '76ef965dd961'
down_revision: str | None = 'd6808b67ffea'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Cần cho cột `knowledge_chunks.embedding` (Vector) — chạy idempotent, an toàn nếu đã có.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('models',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('model_id', sa.String(length=150), nullable=False),
    sa.Column('base_url', sa.String(length=255), nullable=True),
    sa.Column('is_embedding', sa.Boolean(), nullable=False),
    sa.Column('extra_config', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_models_slug'), 'models', ['slug'], unique=True)
    op.create_table('tools',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tools_slug'), 'tools', ['slug'], unique=True)
    op.create_table('knowledge_bases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('embedding_model_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['embedding_model_id'], ['models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_bases_slug'), 'knowledge_bases', ['slug'], unique=True)
    op.create_table('agent_knowledge_bases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('kb_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['kb_id'], ['knowledge_bases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'kb_id')
    )
    op.create_index(op.f('ix_agent_knowledge_bases_agent_id'), 'agent_knowledge_bases', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_knowledge_bases_kb_id'), 'agent_knowledge_bases', ['kb_id'], unique=False)
    op.create_table('agent_tools',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('tool_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'tool_id')
    )
    op.create_index(op.f('ix_agent_tools_agent_id'), 'agent_tools', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_tools_tool_id'), 'agent_tools', ['tool_id'], unique=False)
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('default_model_id', sa.Integer(), nullable=True),
    sa.Column('default_agent_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['default_agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['default_model_id'], ['models.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_chunks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kb_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['kb_id'], ['knowledge_bases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_chunks_kb_id'), 'knowledge_chunks', ['kb_id'], unique=False)
    op.add_column('agents', sa.Column('model_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'agents', 'models', ['model_id'], ['id'])
    op.drop_column('agents', 'model')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('model', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'agents', type_='foreignkey')
    op.drop_column('agents', 'model_id')
    op.drop_index(op.f('ix_knowledge_chunks_kb_id'), table_name='knowledge_chunks')
    op.drop_table('knowledge_chunks')
    op.drop_table('app_settings')
    op.drop_index(op.f('ix_agent_tools_tool_id'), table_name='agent_tools')
    op.drop_index(op.f('ix_agent_tools_agent_id'), table_name='agent_tools')
    op.drop_table('agent_tools')
    op.drop_index(op.f('ix_agent_knowledge_bases_kb_id'), table_name='agent_knowledge_bases')
    op.drop_index(op.f('ix_agent_knowledge_bases_agent_id'), table_name='agent_knowledge_bases')
    op.drop_table('agent_knowledge_bases')
    op.drop_index(op.f('ix_knowledge_bases_slug'), table_name='knowledge_bases')
    op.drop_table('knowledge_bases')
    op.drop_index(op.f('ix_tools_slug'), table_name='tools')
    op.drop_table('tools')
    op.drop_index(op.f('ix_models_slug'), table_name='models')
    op.drop_table('models')
    # ### end Alembic commands ###
