"""add credentials table

Revision ID: d31d1bde1c9e
Revises: a1c2e3f4b5d6
Create Date: 2026-08-23 22:37:46.766684

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "d31d1bde1c9e"
down_revision: str | None = "a1c2e3f4b5d6"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "credentials",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("provider", sa.String(length=30), nullable=False),
        sa.Column("ciphertext", sa.LargeBinary(), nullable=False),
        sa.Column("is_valid", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_credentials_provider"), "credentials", ["provider"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_credentials_provider"), table_name="credentials")
    op.drop_table("credentials")
    # ### end Alembic commands ###
