"""add agent entity, agent_delegations, conversation.agent_id

Revision ID: d6808b67ffea
Revises: 37ae57658663
Create Date: 2026-08-18 18:19:07.007605

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = 'd6808b67ffea'
down_revision: str | None = '37ae57658663'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('system_prompt', sa.String(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('is_orchestrator', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agents_slug'), 'agents', ['slug'], unique=True)
    op.create_table('agent_delegations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('orchestrator_agent_id', sa.Integer(), nullable=False),
    sa.Column('sub_agent_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['orchestrator_agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sub_agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('orchestrator_agent_id', 'sub_agent_id')
    )
    op.create_index(op.f('ix_agent_delegations_orchestrator_agent_id'), 'agent_delegations', ['orchestrator_agent_id'], unique=False)
    op.create_index(op.f('ix_agent_delegations_sub_agent_id'), 'agent_delegations', ['sub_agent_id'], unique=False)
    op.add_column('conversations', sa.Column('agent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'conversations', 'agents', ['agent_id'], ['id'], ondelete='SET NULL')
    op.drop_column('conversations', 'agent')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('agent', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_column('conversations', 'agent_id')
    op.drop_index(op.f('ix_agent_delegations_sub_agent_id'), table_name='agent_delegations')
    op.drop_index(op.f('ix_agent_delegations_orchestrator_agent_id'), table_name='agent_delegations')
    op.drop_table('agent_delegations')
    op.drop_index(op.f('ix_agents_slug'), table_name='agents')
    op.drop_table('agents')
    # ### end Alembic commands ###
